name       : openblas
version    : 0.3.20
release    : 24
source     :
    - https://github.com/xianyi/OpenBLAS/releases/download/v0.3.20/OpenBLAS-0.3.20.tar.gz : 8495c9affc536253648e942908e88e097f2ec7753ede55aca52e5dead3029e3c
license    : BSD-3-Clause
component  : programming.library
optimize   :
    - speed
    - lto
avx2       : yes
summary    : OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
patterns   :
    - /usr/lib64/libopenblas_core2p*.so
setup      : |
    %apply_patches
build      : |
    if [[ ! -z "${AVX2BUILD}" ]]; then
        export _target="HASWELL"
    else
        export _target="CORE2"
    fi
    # Need to patch out tests or it will break RE_LAPACKE option in future
    %make libs netlib shared CROSS_SUFFIX=x86_64-solus-linux-gcc- \
        F_COMPILER=GFORTRAN \
        NO_LAPACK=1 \
        NO_LAPACKE=1 \
        USE_THREAD=1 \
        DYNAMIC_THREADS=1 \
        NUM_THREADS=128 \
        USE_OPENMP=1 \
        TARGET=${_target}
install    : |
    %make_install OPENBLAS_LIBRARY_DIR=%libdir% \
                  NO_LAPACK=1 \
                  NO_LAPACKE=1 \
                  NO_STATIC=1 \
                  PREFIX=/usr
    rmdir $installdir/usr/bin
#check      : |
#    if [[ ! -z "${AVX2BUILD}" ]]; then
#        export _target="HASWELL"
#    else
#        export _target="CORE2"
#    fi
#    %make tests blas-test lapack-test \
#          F_COMPILER=GFORTRAN \
#          USE_THREAD=1 \
#          DYNAMIC_THREADS=1 \
#          NUM_THREADS=128 \
#          USE_OPENMP=1 \
#          TARGET=${_target}
