name       : openblas
version    : 0.2.20
release    : 10
source     :
    - http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz : 5ef38b15d9c652985774869efd548b8e3e972e1e99475c673b25537ed7bcf394
license    : BSD-3-Clause
component  : programming
optimize   : speed
avx2       : yes
summary    : OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
patterns   :
    - /usr/lib64/libopenblas_core2p*.so
build      : |
    if [[ ! -z "${AVX2BUILD}" ]]; then
        export _target="HASWELL"
    else
        export _target="CORE2"
    fi
    # Need to patch out tests or it will break RE_LAPACKE option in future
    %make libs netlib shared CROSS_SUFFIX=x86_64-solus-linux-gcc- \
        F_COMPILER=GFORTRAN \
        USE_THREAD=1 \
        TARGET=${_target}
install    : |
    %make_install OPENBLAS_LIBRARY_DIR=%libdir% \
                  NO_STATIC=1 \
                  PREFIX=/usr
    rmdir $installdir/usr/bin
check      : |
    if [[ ! -z "${AVX2BUILD}" ]]; then
        export _target="HASWELL"
    else
        export _target="CORE2"
    fi
    %make tests blas-test lapack-test \
          F_COMPILER=GFORTRAN \
          USE_THREAD=1 \
          TARGET=${_target}
