name       : openblas
version    : 0.2.18
release    : 1
source     :
    - http://github.com/xianyi/OpenBLAS/archive/v0.2.18.tar.gz : 7d9f8d4ea4a65ab68088f3bb557f03a7ac9cb5036ef2ba30546c3a28774a4112
license    : BSD-3-Clause
component  : programming
summary    : OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
setup      : |
    %cmake
build      : |
    %make NO_STATIC=1 USE_OPENMP=0 TARGET=CORE2
install    : |
    install -d -m 00755 $installdir/usr/lib64
    install -m 00755 $workdir/lib/*.so* $installdir/usr/lib64
