name       : openblas
version    : 0.2.19
release    : 7
source     :
    - http://github.com/xianyi/OpenBLAS/archive/v0.2.19.tar.gz : 9c40b5e4970f27c5f6911cb0a28aa26b6c83f17418b69f8e5a116bb983ca8557
license    : BSD-3-Clause
component  : programming
optimize   : speed
avx2       : yes
summary    : OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
patterns   :
    - /usr/lib64/libopenblas_core2p*.so
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-CL-optimizations.patch
build      : |
    %make libs netlib shared CROSS_SUFFIX=x86_64-solus-linux-gcc- \
        F_COMPILER=GFORTRAN \
        NO_STATIC=1 \
        USE_THREAD=1 \
        TARGET=CORE2
install    : |
    %make_install OPENBLAS_LIBRARY_DIR=%libdir% \
        NO_STATIC=1 \
        PREFIX=/usr
    rmdir $installdir/usr/bin
