name       : openblas
version    : 0.2.18
release    : 3
source     :
    - http://github.com/xianyi/OpenBLAS/archive/v0.2.18.tar.gz : 7d9f8d4ea4a65ab68088f3bb557f03a7ac9cb5036ef2ba30546c3a28774a4112
license    : BSD-3-Clause
component  : programming
summary    : OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
description: |
    OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
patterns   : 
    - /usr/lib64/libopenblas_core2p*.so
build      : |
    %make CROSS_SUFFIX=x86_64-solus-linux-gcc- \
        NO_CBLAS=1 \
        NO_LAPACK=1 \
        NO_STATIC=1 \
        TARGET=CORE2
install    : |
    %make_install NO_CBLAS=1 \
        NO_LAPACK=1 \
        NO_STATIC=1 \
        OPENBLAS_LIBRARY_DIR=%libdir% \
        PREFIX=/usr
    rmdir $installdir/usr/bin
